server {
    listen 80;

    root /frontend;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /backend-api/ {
        proxy_pass http://backend:6789;
    }

    location /open-webui. {
        proxy_pass http://open-webui:8080;
    }
}